// Detailed Star-Trek station & NPC-ship mesh builders (primitives only, units = km).
// Generated by a parallel design workflow; each builder returns a THREE.Group with
// group.userData.blinkers = [meshes] for the nav-light pulse in fleet.js.

export function buildSpacedock(THREE) {
  const g = new THREE.Group();
  g.userData.blinkers = [];

  const hull = new THREE.MeshStandardMaterial({ color: 0xccd3dd, metalness: 0.45, roughness: 0.4 });
  const dark = new THREE.MeshStandardMaterial({ color: 0x6b7480, metalness: 0.6, roughness: 0.5 });
  const deep = new THREE.MeshStandardMaterial({ color: 0x3a4149, metalness: 0.55, roughness: 0.6 });
  const windows = new THREE.MeshStandardMaterial({ color: 0x9fd8ff, emissive: 0x7fc4ff, emissiveIntensity: 0.7 });
  const amber = new THREE.MeshStandardMaterial({ color: 0xd89030, emissive: 0xff9920, emissiveIntensity: 1.2 });
  const red = new THREE.MeshStandardMaterial({ color: 0xff3018, emissive: 0xff2a10, emissiveIntensity: 2 });

  function add(geo, mat, x, y, z, rx, ry, rz) {
    const m = new THREE.Mesh(geo, mat);
    m.position.set(x, y, z);
    m.rotation.set(rx || 0, ry || 0, rz || 0);
    g.add(m);
    return m;
  }

  const seg = 48;

  // (1) main oblate dome as stacked tapering cylinders, y from 0.25 to 3.05, max radius 2.5 (5 km diameter)
  add(new THREE.CylinderGeometry(2.5, 2.5, 0.6, seg), hull, 0, 1.5, 0);
  add(new THREE.CylinderGeometry(2.0, 2.42, 0.5, seg), hull, 0, 2.05, 0);
  add(new THREE.CylinderGeometry(1.35, 2.0, 0.45, seg), hull, 0, 2.525, 0);
  add(new THREE.CylinderGeometry(0.7, 1.35, 0.3, seg), hull, 0, 2.9, 0);
  const cupola = add(new THREE.SphereGeometry(0.55, 32, 16), hull, 0, 3.0, 0);
  cupola.scale.set(1, 0.45, 1);
  add(new THREE.CylinderGeometry(2.42, 1.9, 0.35, seg), hull, 0, 1.025, 0);
  add(new THREE.CylinderGeometry(1.9, 1.2, 0.3, seg), dark, 0, 0.7, 0);
  add(new THREE.CylinderGeometry(1.2, 0.62, 0.3, seg), dark, 0, 0.4, 0);

  // (2) tapering neck, y 0.25 down to -1.6
  add(new THREE.CylinderGeometry(0.55, 0.45, 1.85, 32), hull, 0, -0.675, 0);

  // (3) counterweight stack flaring into the lower skirt dome, bottom at y = -3.96
  add(new THREE.CylinderGeometry(0.6, 0.6, 0.3, 32), dark, 0, -1.7, 0);
  add(new THREE.CylinderGeometry(0.6, 1.35, 0.7, seg), hull, 0, -2.2, 0);
  add(new THREE.CylinderGeometry(1.4, 1.4, 0.55, seg), hull, 0, -2.825, 0);
  add(new THREE.CylinderGeometry(1.4, 0.95, 0.42, seg), hull, 0, -3.31, 0);
  const bdome = add(new THREE.SphereGeometry(1.0, 32, 16), dark, 0, -3.5, 0);
  bdome.scale.set(0.95, 0.46, 0.95);

  // (4) antenna spire, 1 km tall, tip reaches y = +4 with the blinker
  add(new THREE.CylinderGeometry(0.018, 0.03, 1.0, 12), dark, 0, 3.47, 0);
  add(new THREE.ConeGeometry(0.12, 0.12, 16), hull, 0, 3.62, 0, Math.PI, 0, 0);
  add(new THREE.TorusGeometry(0.09, 0.016, 8, 24), dark, 0, 3.28, 0, Math.PI / 2, 0, 0);

  // three recessed hangar-door slots around the equator rim, amber-lit frames
  const doorGeo = new THREE.BoxGeometry(0.12, 0.44, 1.3);
  const frameH = new THREE.BoxGeometry(0.14, 0.06, 1.42);
  const frameV = new THREE.BoxGeometry(0.14, 0.56, 0.06);
  for (let i = 0; i < 3; i++) {
    const a = i * Math.PI * 2 / 3;
    const c = Math.cos(a), s = Math.sin(a);
    const tx = -s, tz = c;
    add(doorGeo, deep, 2.46 * c, 1.5, 2.46 * s, 0, -a, 0);
    add(frameH, amber, 2.46 * c, 1.75, 2.46 * s, 0, -a, 0);
    add(frameH, amber, 2.46 * c, 1.25, 2.46 * s, 0, -a, 0);
    add(frameV, amber, 2.46 * c + 0.68 * tx, 1.5, 2.46 * s + 0.68 * tz, 0, -a, 0);
    add(frameV, amber, 2.46 * c - 0.68 * tx, 1.5, 2.46 * s - 0.68 * tz, 0, -a, 0);
  }

  // two rows of discrete lit windows on the rim band, skipping the door slots
  const winGeo = new THREE.BoxGeometry(0.03, 0.08, 0.14);
  const third = Math.PI * 2 / 3;
  for (let r = 0; r < 2; r++) {
    const y = r === 0 ? 1.66 : 1.34;
    for (let k = 0; k < 24; k++) {
      const a = k * Math.PI / 12;
      const m = a % third;
      if (Math.min(m, third - m) < 0.31) continue;
      add(winGeo, windows, 2.505 * Math.cos(a), y, 2.505 * Math.sin(a), 0, -a, 0);
    }
  }

  // continuous lit window strips: upper dome (2), neck, skirt
  add(new THREE.CylinderGeometry(2.205, 2.255, 0.06, seg), windows, 0, 2.05, 0);
  add(new THREE.CylinderGeometry(1.688, 1.774, 0.06, seg), windows, 0, 2.5, 0);
  add(new THREE.CylinderGeometry(0.525, 0.525, 0.07, 32), windows, 0, -0.5, 0);
  add(new THREE.CylinderGeometry(1.415, 1.415, 0.07, seg), windows, 0, -2.72, 0);

  // (5) four docking pylons off the lower skirt with amber port lights
  const armGeo = new THREE.BoxGeometry(1.1, 0.14, 0.2);
  const hubGeo = new THREE.CylinderGeometry(0.2, 0.2, 0.32, 16);
  const ringGeo = new THREE.TorusGeometry(0.14, 0.03, 8, 20);
  const portGeo = new THREE.SphereGeometry(0.05, 10, 8);
  for (let i = 0; i < 4; i++) {
    const a = i * Math.PI / 2;
    const c = Math.cos(a), s = Math.sin(a);
    add(armGeo, hull, 1.85 * c, -2.8, 1.85 * s, 0, -a, 0);
    add(hubGeo, dark, 2.45 * c, -2.8, 2.45 * s, 0, -a, Math.PI / 2);
    add(ringGeo, deep, 2.62 * c, -2.8, 2.62 * s, 0, Math.PI / 2 - a, 0);
    add(portGeo, amber, 2.66 * c, -2.8, 2.66 * s);
  }

  // blinking navigation lights: spire tip, skirt bottom (red), dome rim 4x (amber)
  const blinkGeo = new THREE.SphereGeometry(0.03, 10, 8);
  function blink(mat, x, y, z) {
    const m = add(blinkGeo, mat.clone(), x, y, z);
    g.userData.blinkers.push(m);
    return m;
  }
  blink(red, 0, 3.97, 0);
  blink(red, 0, -3.97, 0);
  for (let i = 0; i < 4; i++) {
    const a = Math.PI / 4 + i * Math.PI / 2;
    blink(amber, 2.51 * Math.cos(a), 1.81, 2.51 * Math.sin(a));
  }

  return g;
}

export function buildRingStation(THREE) {
  const g = new THREE.Group();
  const hull = new THREE.MeshStandardMaterial({ color: 0xccd3dd, metalness: 0.45, roughness: 0.4 });
  // the main ring gets its own hull instance so greeble can lay windows out in
  // ring coordinates (see _ringWin branch in greeble.js) instead of confetti
  const ringHull = new THREE.MeshStandardMaterial({ color: 0xccd3dd, metalness: 0.45, roughness: 0.4 });
  ringHull.userData._ringWin = true;
  const dark = new THREE.MeshStandardMaterial({ color: 0x6b7480, metalness: 0.6, roughness: 0.5 });
  const deep = new THREE.MeshStandardMaterial({ color: 0x3a4149, metalness: 0.55, roughness: 0.6 });
  const windows = new THREE.MeshStandardMaterial({ color: 0x9fd8ff, emissive: 0x7fc4ff, emissiveIntensity: 0.7 });
  const amber = new THREE.MeshStandardMaterial({ color: 0xd89030, emissive: 0xff9920, emissiveIntensity: 1.2 });
  const red = new THREE.MeshStandardMaterial({ color: 0xff3018, emissive: 0xff2a10, emissiveIntensity: 2 });
  g.userData.blinkers = [];

  // Central hub: cylinder r=0.35, h=1.4, with dark trim rings and lit window bands
  const hub = new THREE.Mesh(new THREE.CylinderGeometry(0.35, 0.35, 1.4, 48), hull);
  g.add(hub);

  const trimGeo = new THREE.CylinderGeometry(0.365, 0.365, 0.09, 48);
  for (let s = -1; s <= 1; s += 2) {
    const t = new THREE.Mesh(trimGeo, dark);
    t.position.y = 0.655 * s;
    g.add(t);
  }

  const bandGeo = new THREE.CylinderGeometry(0.354, 0.354, 0.028, 48);
  for (let i = 0; i < 4; i++) {
    const b = new THREE.Mesh(bandGeo, windows);
    b.position.y = -0.51 + i * 0.34;
    g.add(b);
  }

  // Domed caps (flattened hemispheres) keep total height ~1.5
  const domeGeo = new THREE.SphereGeometry(0.35, 32, 12, 0, Math.PI * 2, 0, Math.PI / 2);
  const topDome = new THREE.Mesh(domeGeo, hull);
  topDome.position.y = 0.7;
  topDome.scale.y = 0.18;
  const botDome = new THREE.Mesh(domeGeo, hull);
  botDome.position.y = -0.7;
  botDome.scale.y = 0.18;
  botDome.rotation.x = Math.PI;
  g.add(topDome, botDome);

  // Hub greeble boxes
  const grebGeo = new THREE.BoxGeometry(0.05, 0.12, 0.14);
  for (let i = 0; i < 6; i++) {
    const a = i * Math.PI / 3 + 0.26;
    const m = new THREE.Mesh(grebGeo, deep);
    m.position.set(Math.cos(a) * 0.36, i % 2 === 0 ? 0.32 : -0.32, Math.sin(a) * 0.36);
    m.rotation.y = -a;
    g.add(m);
  }

  // Main ring: torus r=1.8, tube=0.16, horizontal, with dark rib bands top/bottom
  const ring = new THREE.Mesh(new THREE.TorusGeometry(1.8, 0.16, 24, 96), ringHull);
  ring.rotation.x = Math.PI / 2;
  g.add(ring);

  const ribGeo = new THREE.TorusGeometry(1.8, 0.045, 10, 96);
  for (let s = -1; s <= 1; s += 2) {
    const rb = new THREE.Mesh(ribGeo, deep);
    rb.rotation.x = Math.PI / 2;
    rb.position.y = 0.15 * s;
    g.add(rb);
  }

  // Four boxy spokes hub -> ring, each with a dark conduit on top
  const spokeGeo = new THREE.BoxGeometry(1.36, 0.1, 0.22);
  const conduitGeo = new THREE.BoxGeometry(1.2, 0.05, 0.1);
  for (let i = 0; i < 4; i++) {
    const a = i * Math.PI / 2;
    const c = Math.cos(a);
    const s = Math.sin(a);
    const sp = new THREE.Mesh(spokeGeo, hull);
    sp.position.set(c, 0, s);
    sp.rotation.y = -a;
    const cd = new THREE.Mesh(conduitGeo, deep);
    cd.position.set(c, 0.075, s);
    cd.rotation.y = -a;
    g.add(sp, cd);
  }

  // Eight outward-facing docking modules with dark plates and amber port lights (max extent exactly 2.0)
  const modGeo = new THREE.BoxGeometry(0.2, 0.2, 0.3);
  const plateGeo = new THREE.BoxGeometry(0.02, 0.14, 0.22);
  const portGeo = new THREE.SphereGeometry(0.05, 12, 8);
  for (let i = 0; i < 8; i++) {
    const a = i * Math.PI / 4 + Math.PI / 8;
    const c = Math.cos(a);
    const s = Math.sin(a);
    const mod = new THREE.Mesh(modGeo, hull);
    mod.position.set(c * 1.88, 0, s * 1.88);
    mod.rotation.y = -a;
    const pl = new THREE.Mesh(plateGeo, dark);
    pl.position.set(c * 1.99, 0, s * 1.99);
    pl.rotation.y = -a;
    const pt = new THREE.Mesh(portGeo, amber);
    pt.position.set(c * 1.985, 0, s * 1.985);
    pt.rotation.y = -a;
    pt.scale.x = 0.3;
    g.add(mod, pl, pt);
  }

  // 16 emissive window strips along the outer equator of the torus
  const winGeo = new THREE.BoxGeometry(0.015, 0.05, 0.18);
  for (let i = 0; i < 16; i++) {
    const a = i * Math.PI / 8 + Math.PI / 16;
    const w = new THREE.Mesh(winGeo, windows);
    w.position.set(Math.cos(a) * 1.956, 0, Math.sin(a) * 1.956);
    w.rotation.y = -a;
    g.add(w);
  }

  // Radiator fins: crossed flat dark panels above and below hub midline
  const finGeo = new THREE.BoxGeometry(1.5, 0.3, 0.03);
  for (let i = 0; i < 4; i++) {
    const f = new THREE.Mesh(finGeo, dark);
    f.position.y = i < 2 ? 0.5 : -0.5;
    f.rotation.y = (i % 2) * Math.PI / 2;
    g.add(f);
  }

  // Dish antenna assembly on the top cap
  const dish = new THREE.Group();
  const mast = new THREE.Mesh(new THREE.CylinderGeometry(0.012, 0.012, 0.09, 8), dark);
  mast.position.y = 0.045;
  const bowl = new THREE.Mesh(new THREE.SphereGeometry(0.09, 16, 8, 0, Math.PI * 2, 0, Math.PI / 2), hull);
  bowl.position.y = 0.1;
  bowl.scale.y = 0.4;
  bowl.rotation.x = Math.PI;
  const feed = new THREE.Mesh(new THREE.CylinderGeometry(0.005, 0.005, 0.07, 6), deep);
  feed.position.y = 0.125;
  dish.add(mast, bowl, feed);
  dish.position.set(0.14, 0.755, 0);
  dish.rotation.z = -0.4;
  g.add(dish);

  // Whip antennae on the bottom cap
  const antGeo = new THREE.CylinderGeometry(0.008, 0.008, 0.12, 6);
  const a1 = new THREE.Mesh(antGeo, dark);
  a1.position.set(0.1, -0.81, 0.08);
  const a2 = new THREE.Mesh(antGeo, dark);
  a2.position.set(-0.13, -0.8, -0.06);
  a2.scale.y = 0.7;
  g.add(a1, a2);

  // Blinking navigation lights: top cap, bottom cap, 4 ring cardinal points
  const blinkGeo = new THREE.SphereGeometry(0.018, 8, 8);
  const topB = new THREE.Mesh(blinkGeo, red.clone());
  topB.position.y = 0.775;
  const botB = new THREE.Mesh(blinkGeo, red.clone());
  botB.position.y = -0.775;
  g.add(topB, botB);
  g.userData.blinkers.push(topB, botB);
  for (let i = 0; i < 4; i++) {
    const a = i * Math.PI / 2;
    const b = new THREE.Mesh(blinkGeo, (i % 2 === 0 ? red : amber).clone());
    b.position.set(Math.cos(a) * 1.982, 0, Math.sin(a) * 1.982);
    g.add(b);
    g.userData.blinkers.push(b);
  }

  return g;
}

export function buildGateway(THREE) {
  const g = new THREE.Group();
  g.userData.blinkers = [];

  const hull = new THREE.MeshStandardMaterial({ color: 0xccd3dd, metalness: 0.45, roughness: 0.4 });
  const dark = new THREE.MeshStandardMaterial({ color: 0x6b7480, metalness: 0.6, roughness: 0.5 });
  const deep = new THREE.MeshStandardMaterial({ color: 0x3a4149, metalness: 0.55, roughness: 0.6 });
  const windows = new THREE.MeshStandardMaterial({ color: 0x9fd8ff, emissive: 0x7fc4ff, emissiveIntensity: 0.7 });
  const amber = new THREE.MeshStandardMaterial({ color: 0xd89030, emissive: 0xff9920, emissiveIntensity: 1.2 });
  const red = new THREE.MeshStandardMaterial({ color: 0xff3018, emissive: 0xff2a10, emissiveIntensity: 2 });

  const ringY = 0.7;

  // two main torus rings with lit window bands on the outer equator
  const ringGeo = new THREE.TorusGeometry(2.4, 0.14, 16, 96);
  const bandGeo = new THREE.TorusGeometry(2.548, 0.02, 8, 96);
  for (let s = -1; s <= 1; s += 2) {
    const ring = new THREE.Mesh(ringGeo, hull);
    ring.rotation.x = Math.PI / 2;
    ring.position.y = s * ringY;
    g.add(ring);
    const band = new THREE.Mesh(bandGeo, windows);
    band.rotation.x = Math.PI / 2;
    band.position.y = s * ringY;
    g.add(band);
  }

  // six vertical truss columns joining the rings (twin rails + mid brace)
  const railGeo = new THREE.BoxGeometry(0.07, 1.52, 0.07);
  const braceGeo = new THREE.BoxGeometry(0.05, 0.05, 0.3);
  for (let i = 0; i < 6; i++) {
    const a = (i * Math.PI) / 3;
    const ca = Math.cos(a), sa = Math.sin(a);
    for (let t = -1; t <= 1; t += 2) {
      const rail = new THREE.Mesh(railGeo, dark);
      rail.position.set(2.4 * ca - t * 0.09 * sa, 0, 2.4 * sa + t * 0.09 * ca);
      rail.rotation.y = -a;
      g.add(rail);
    }
    const brace = new THREE.Mesh(braceGeo, deep);
    brace.position.set(2.4 * ca, 0, 2.4 * sa);
    brace.rotation.y = -a;
    g.add(brace);
  }

  // diagonal spokes from the hub out to each ring
  const spokeLen = Math.sqrt(2.05 * 2.05 + 0.5 * 0.5);
  const spokeGeo = new THREE.CylinderGeometry(0.05, 0.05, spokeLen, 10);
  const upAxis = new THREE.Vector3(0, 1, 0);
  for (let i = 0; i < 4; i++) {
    const a = Math.PI / 4 + (i * Math.PI) / 2;
    const ca = Math.cos(a), sa = Math.sin(a);
    for (let s = -1; s <= 1; s += 2) {
      const spoke = new THREE.Mesh(spokeGeo, dark);
      spoke.position.set(1.375 * ca, s * 0.45, 1.375 * sa);
      const dir = new THREE.Vector3(2.05 * ca, s * 0.5, 2.05 * sa).normalize();
      spoke.quaternion.setFromUnitVectors(upAxis, dir);
      g.add(spoke);
    }
  }

  // central hub sphere with window bands and amber equator strip
  const hub = new THREE.Mesh(new THREE.SphereGeometry(0.5, 48, 32), hull);
  g.add(hub);
  const hubBandGeo = new THREE.CylinderGeometry(0.479, 0.479, 0.035, 48);
  for (let s = -1; s <= 1; s += 2) {
    const hb = new THREE.Mesh(hubBandGeo, windows);
    hb.position.y = s * 0.16;
    g.add(hb);
  }
  const equator = new THREE.Mesh(new THREE.CylinderGeometry(0.506, 0.506, 0.05, 48), amber);
  g.add(equator);
  const topCollar = new THREE.Mesh(new THREE.CylinderGeometry(0.2, 0.24, 0.1, 24), deep);
  topCollar.position.y = 0.46;
  g.add(topCollar);
  const botCollar = new THREE.Mesh(new THREE.CylinderGeometry(0.24, 0.18, 0.1, 24), deep);
  botCollar.position.y = -0.46;
  g.add(botCollar);

  // ventral antenna mast
  const mast = new THREE.Mesh(new THREE.CylinderGeometry(0.025, 0.025, 0.5, 8), dark);
  mast.position.y = -0.75;
  g.add(mast);

  // blinker helper
  const blinkGeo = new THREE.SphereGeometry(0.045, 12, 10);
  const addBlink = (mat, x, y, z) => {
    const b = new THREE.Mesh(blinkGeo, mat.clone());
    b.position.set(x, y, z);
    g.add(b);
    g.userData.blinkers.push(b);
  };
  addBlink(red, 0, -1.03, 0);

  // large parabolic comms dish, tilted outward on top of the hub
  const pedestal = new THREE.Mesh(new THREE.CylinderGeometry(0.08, 0.11, 0.34, 16), dark);
  pedestal.position.y = 0.63;
  g.add(pedestal);
  const joint = new THREE.Mesh(new THREE.SphereGeometry(0.1, 16, 12), dark);
  joint.position.set(0.05, 0.79, 0);
  g.add(joint);
  const dish = new THREE.Group();
  dish.position.set(0.12, 0.84, 0);
  dish.rotation.z = -0.6;
  g.add(dish);
  const cone = new THREE.Mesh(new THREE.ConeGeometry(0.6, 0.16, 48), hull);
  cone.rotation.x = Math.PI;
  dish.add(cone);
  const face = new THREE.Mesh(new THREE.RingGeometry(0.06, 0.58, 48), deep);
  face.rotation.x = -Math.PI / 2;
  face.position.y = 0.082;
  dish.add(face);
  const rim = new THREE.Mesh(new THREE.TorusGeometry(0.6, 0.03, 10, 48), hull);
  rim.rotation.x = Math.PI / 2;
  rim.position.y = 0.08;
  dish.add(rim);
  const feed = new THREE.Mesh(new THREE.CylinderGeometry(0.022, 0.022, 0.38, 8), dark);
  feed.position.y = 0.25;
  dish.add(feed);
  const feedHead = new THREE.Mesh(new THREE.CylinderGeometry(0.05, 0.05, 0.07, 12), deep);
  feedHead.position.y = 0.46;
  dish.add(feedHead);
  const dishTip = new THREE.Mesh(blinkGeo, red.clone());
  dishTip.position.y = 0.52;
  dish.add(dishTip);
  g.userData.blinkers.push(dishTip);

  // eight docking nubs on the outer face of the upper ring (tips reach 2.75 km radius = 5.5 km overall diameter)
  const nubGeo = new THREE.CylinderGeometry(0.075, 0.055, 0.3, 12);
  for (let i = 0; i < 8; i++) {
    const a = (i * Math.PI) / 4;
    const nub = new THREE.Mesh(nubGeo, hull);
    nub.position.set(2.6 * Math.cos(a), ringY, 2.6 * Math.sin(a));
    nub.rotation.set(0, -a, Math.PI / 2);
    g.add(nub);
  }

  // fuel tank cluster on a truss cradle under the lower ring
  const plate = new THREE.Mesh(new THREE.BoxGeometry(0.62, 0.05, 0.62), deep);
  plate.position.set(2.4, -0.945, 0);
  g.add(plate);
  const hangGeo = new THREE.BoxGeometry(0.06, 0.12, 0.06);
  for (let s = -1; s <= 1; s += 2) {
    const hg = new THREE.Mesh(hangGeo, dark);
    hg.position.set(2.4, -0.875, s * 0.16);
    g.add(hg);
  }
  const cradleRailGeo = new THREE.BoxGeometry(0.05, 0.05, 0.62);
  for (let s = -1; s <= 1; s += 2) {
    const cr = new THREE.Mesh(cradleRailGeo, deep);
    cr.position.set(2.4 + s * 0.2, -0.995, 0);
    g.add(cr);
  }
  const tankGeo = new THREE.CapsuleGeometry(0.085, 0.17, 6, 16);
  for (let i = 0; i < 4; i++) {
    const tx = i < 2 ? -0.13 : 0.13;
    const tz = i % 2 === 0 ? -0.13 : 0.13;
    const tank = new THREE.Mesh(tankGeo, dark);
    tank.position.set(2.4 + tx, -1.14, tz);
    g.add(tank);
  }

  // greeble module pods on top of the upper ring
  const podGeo = new THREE.BoxGeometry(0.24, 0.1, 0.36);
  for (let i = 0; i < 6; i++) {
    const a = Math.PI / 12 + (i * Math.PI) / 3;
    const pod = new THREE.Mesh(podGeo, i % 2 === 0 ? hull : deep);
    pod.position.set(2.4 * Math.cos(a), 0.87, 2.4 * Math.sin(a));
    pod.rotation.y = -a;
    g.add(pod);
  }

  // navigation blinkers: four on each ring at the cardinal points
  for (let i = 0; i < 4; i++) {
    const a = (i * Math.PI) / 2;
    const ca = Math.cos(a), sa = Math.sin(a);
    addBlink(i % 2 === 0 ? red : amber, 2.4 * ca, 0.87, 2.4 * sa);
    addBlink(i % 2 === 0 ? amber : red, 2.4 * ca, -0.87, 2.4 * sa);
  }

  return g;
}

export function buildISS(THREE) {
  const g = new THREE.Group();
  const hull = new THREE.MeshStandardMaterial({ color: 0xccd3dd, metalness: 0.45, roughness: 0.4 });
  const dark = new THREE.MeshStandardMaterial({ color: 0x6b7480, metalness: 0.6, roughness: 0.5 });
  const deep = new THREE.MeshStandardMaterial({ color: 0x3a4149, metalness: 0.55, roughness: 0.6 });
  const windows = new THREE.MeshStandardMaterial({ color: 0x9fd8ff, emissive: 0x7fc4ff, emissiveIntensity: 0.7 });
  const amber = new THREE.MeshStandardMaterial({ color: 0xd89030, emissive: 0xff9920, emissiveIntensity: 1.2 });
  const red = new THREE.MeshStandardMaterial({ color: 0xff3018, emissive: 0xff2a10, emissiveIntensity: 2 });
  const solar = new THREE.MeshStandardMaterial({ color: 0x2a4a7f, metalness: 0.35, roughness: 0.55 });
  g.userData.blinkers = [];

  const yt = 0.0035;
  const ym = -0.0035;

  function add(parent, geo, mat, x, y, z, rx, ry, rz) {
    const m = new THREE.Mesh(geo, mat);
    m.position.set(x, y, z);
    if (rx) m.rotation.x = rx;
    if (ry) m.rotation.y = ry;
    if (rz) m.rotation.z = rz;
    parent.add(m);
    return m;
  }

  // main truss: 13 segments, alternating notch look, exact 0.109 km span
  const nSeg = 13;
  const segL = 0.109 / nSeg;
  const trussA = new THREE.BoxGeometry(segL, 0.004, 0.004);
  const trussB = new THREE.BoxGeometry(segL, 0.0032, 0.0032);
  for (let i = 0; i < nSeg; i++) {
    add(g, i % 2 ? trussB : trussA, i % 2 ? dark : hull, -0.0545 + segL * (i + 0.5), yt, 0);
  }

  // SARJ rotary joints
  const sarjGeo = new THREE.CylinderGeometry(0.0027, 0.0027, 0.0026, 16);
  add(g, sarjGeo, dark, 0.0285, yt, 0, 0, 0, Math.PI / 2);
  add(g, sarjGeo, dark, -0.0285, yt, 0, 0, 0, Math.PI / 2);

  // battery / avionics greebles on truss
  const batGeo = new THREE.BoxGeometry(0.0026, 0.0022, 0.0026);
  for (let i = 0; i < 4; i++) {
    const bx = (i < 2 ? -1 : 1) * (0.014 + (i % 2) * 0.008);
    add(g, batGeo, deep, bx, yt + 0.0031, 0);
  }

  // 4 solar array wings (2 per truss end), each with mast + 2 co-rotating blankets
  const panelGeo = new THREE.BoxGeometry(0.012, 0.0002, 0.034);
  const mastGeo = new THREE.CylinderGeometry(0.0005, 0.0005, 0.073, 6);
  const wingX = [0.0345, 0.0485];
  for (let s = -1; s <= 1; s += 2) {
    for (let w = 0; w < 2; w++) {
      const wing = new THREE.Group();
      wing.position.set(s * wingX[w], yt, 0);
      wing.rotation.x = (w % 2 ? -1 : 1) * 0.16;
      add(wing, mastGeo, dark, 0, 0, 0, Math.PI / 2, 0, 0);
      add(wing, panelGeo, solar, 0, 0, 0.0195);
      add(wing, panelGeo, solar, 0, 0, -0.0195);
      g.add(wing);
    }
  }

  // module train along Z (Zvezda, Zarya, Unity, Destiny, Harmony, PMA)
  const modules = [
    [0.0021, 0.015, 0.0265, hull],
    [0.0021, 0.014, 0.012, hull],
    [0.0023, 0.006, 0.002, hull],
    [0.0022, 0.011, -0.0065, hull],
    [0.0023, 0.009, -0.0165, hull],
    [0.0015, 0.004, -0.023, dark]
  ];
  for (let i = 0; i < modules.length; i++) {
    const md = modules[i];
    add(g, new THREE.CylinderGeometry(md[0], md[0], md[1], 20), md[3], 0, ym, md[2], Math.PI / 2, 0, 0);
  }

  // Zarya small solar arrays
  const zaryaGeo = new THREE.BoxGeometry(0.007, 0.0001, 0.0028);
  add(g, zaryaGeo, solar, 0.0056, ym, 0.012);
  add(g, zaryaGeo, solar, -0.0056, ym, 0.012);

  // docked crew capsule at forward end
  add(g, new THREE.CylinderGeometry(0.0017, 0.0017, 0.004, 16), hull, 0, ym, -0.027, Math.PI / 2, 0, 0);
  add(g, new THREE.ConeGeometry(0.0016, 0.003, 16), dark, 0, ym, -0.0305, -Math.PI / 2, 0, 0);
  add(g, new THREE.TorusGeometry(0.0013, 0.00035, 8, 16), deep, 0, ym, -0.025);

  // aft docking cap on Zvezda
  add(g, new THREE.CylinderGeometry(0.0013, 0.0013, 0.0012, 12), dark, 0, ym, 0.0346, Math.PI / 2, 0, 0);

  // side modules at Harmony (Columbus / Kibo)
  const sideGeo = new THREE.CylinderGeometry(0.0018, 0.0018, 0.007, 16);
  add(g, sideGeo, hull, 0.006, ym, -0.0165, 0, 0, Math.PI / 2);
  add(g, sideGeo, hull, -0.006, ym, -0.0165, 0, 0, Math.PI / 2);

  // cupola underneath
  add(g, new THREE.SphereGeometry(0.0014, 12, 10), dark, 0, ym - 0.0024, 0.002);
  add(g, new THREE.SphereGeometry(0.0008, 10, 8), windows, 0, ym - 0.0032, 0.002);

  // Z1 vertical truss connecting module train to main truss
  add(g, new THREE.BoxGeometry(0.0032, 0.0056, 0.0032), deep, 0, 0, 0);

  // lit window strips on Destiny and Zvezda
  const winGeo = new THREE.BoxGeometry(0.0004, 0.0008, 0.006);
  const winSpots = [[0.0021, -0.0065], [-0.0021, -0.0065], [0.002, 0.0265], [-0.002, 0.0265]];
  for (let i = 0; i < winSpots.length; i++) {
    add(g, winGeo, windows, winSpots[i][0], ym, winSpots[i][1]);
  }

  // aft antennae + dish on Zvezda
  add(g, new THREE.CylinderGeometry(0.0002, 0.0002, 0.005, 6), dark, 0, ym + 0.0012, 0.0365, Math.PI / 2, 0, 0);
  const antGeo = new THREE.CylinderGeometry(0.00015, 0.00015, 0.004, 6);
  add(g, antGeo, dark, 0.0013, ym, 0.0355, Math.PI / 2, 0, 0.5);
  add(g, antGeo, dark, -0.0013, ym, 0.0355, Math.PI / 2, 0, -0.5);
  add(g, new THREE.CylinderGeometry(0.0012, 0.0012, 0.0002, 12), dark, 0.0022, ym + 0.0022, 0.033, 1.2, 0, 0);

  // 3 tilted white radiator panels near center with mounts
  const radGeo = new THREE.BoxGeometry(0.0035, 0.00015, 0.013);
  const mountGeo = new THREE.BoxGeometry(0.0014, 0.0014, 0.0024);
  const radDat = [[-0.0125, 0.55], [-0.0075, 0.8], [0.0105, -0.65]];
  for (let i = 0; i < radDat.length; i++) {
    add(g, radGeo, hull, radDat[i][0], yt - 0.001, -0.0095, radDat[i][1], 0, 0);
    add(g, mountGeo, deep, radDat[i][0], yt, -0.003);
  }

  // blinking navigation lights
  const blinkGeo = new THREE.SphereGeometry(0.0007, 8, 8);
  for (let s = -1; s <= 1; s += 2) {
    const b = add(g, blinkGeo, red.clone(), s * 0.0545, yt, 0);
    g.userData.blinkers.push(b);
  }
  const ab = add(g, blinkGeo, amber.clone(), 0, ym + 0.0012, 0.039);
  g.userData.blinkers.push(ab);

  return g;
}

export function buildFreighter(THREE) {
  const g = new THREE.Group();
  g.userData.blinkers = [];
  const hull = new THREE.MeshStandardMaterial({ color: 0xccd3dd, metalness: 0.45, roughness: 0.4 });
  const dark = new THREE.MeshStandardMaterial({ color: 0x6b7480, metalness: 0.6, roughness: 0.5 });
  const deep = new THREE.MeshStandardMaterial({ color: 0x3a4149, metalness: 0.55, roughness: 0.6 });
  const windows = new THREE.MeshStandardMaterial({ color: 0x9fd8ff, emissive: 0x7fc4ff, emissiveIntensity: 0.7 });
  const amber = new THREE.MeshStandardMaterial({ color: 0xd89030, emissive: 0xff9920, emissiveIntensity: 1.2 });
  const red = new THREE.MeshStandardMaterial({ color: 0xff3018, emissive: 0xff2a10, emissiveIntensity: 2 });
  const cargoMats = [
    new THREE.MeshStandardMaterial({ color: 0x8a6f4a, metalness: 0.3, roughness: 0.7 }),
    new THREE.MeshStandardMaterial({ color: 0x5f6f7a, metalness: 0.3, roughness: 0.7 }),
    new THREE.MeshStandardMaterial({ color: 0x6f5f52, metalness: 0.3, roughness: 0.7 })
  ];

  // crew block at bow (bow face exactly at z = -0.25)
  const crew = new THREE.Mesh(new THREE.BoxGeometry(0.06, 0.042, 0.07), hull);
  crew.position.set(0, 0, -0.215);
  g.add(crew);
  const strip = new THREE.Mesh(new THREE.BoxGeometry(0.062, 0.007, 0.045), windows);
  strip.position.set(0, 0.006, -0.218);
  g.add(strip);
  const dock = new THREE.Mesh(new THREE.CylinderGeometry(0.01, 0.01, 0.01, 16), dark);
  dock.rotation.z = Math.PI / 2;
  dock.position.set(0.033, 0, -0.215);
  g.add(dock);
  const antenna = new THREE.Mesh(new THREE.CylinderGeometry(0.0015, 0.0015, 0.028, 8), dark);
  antenna.position.set(0, 0.035, -0.235);
  g.add(antenna);

  // central spine truss
  const spine = new THREE.Mesh(new THREE.BoxGeometry(0.018, 0.018, 0.36), dark);
  spine.position.set(0, 0, 0);
  g.add(spine);
  const ribGeo = new THREE.BoxGeometry(0.034, 0.034, 0.008);
  for (let i = 0; i < 3; i++) {
    const rib = new THREE.Mesh(ribGeo, deep);
    rib.position.set(0, 0, -0.165 + i * 0.165);
    g.add(rib);
  }

  // 10 containers in two staggered rows (above / below spine), clamped
  const boxGeo = new THREE.BoxGeometry(0.05, 0.05, 0.11);
  const clampGeo = new THREE.BoxGeometry(0.012, 0.05, 0.012);
  for (let i = 0; i < 10; i++) {
    const row = i % 2;
    const idx = (i - row) / 2;
    const z = -0.15 + idx * 0.065 + row * 0.0325;
    const y = row === 0 ? 0.045 : -0.045;
    const c = new THREE.Mesh(boxGeo, cargoMats[i % 3]);
    c.rotation.y = Math.PI / 2;
    c.position.set(0, y, z);
    g.add(c);
    const cl = new THREE.Mesh(clampGeo, deep);
    cl.position.set(0, row === 0 ? 0.028 : -0.028, z);
    g.add(cl);
  }

  // engine block at stern (stern face exactly at z = +0.25)
  const eng = new THREE.Mesh(new THREE.BoxGeometry(0.075, 0.055, 0.08), dark);
  eng.position.set(0, 0, 0.21);
  g.add(eng);
  const nozGeo = new THREE.CylinderGeometry(0.02, 0.017, 0.014, 24);
  [-1, 1].forEach((s) => {
    const n = new THREE.Mesh(nozGeo, amber);
    n.rotation.x = Math.PI / 2;
    n.position.set(s * 0.02, 0, 0.243);
    g.add(n);
  });

  // nav blinkers: red at bow, amber at stern
  const blinkGeo = new THREE.SphereGeometry(0.0035, 10, 8);
  const bowB = new THREE.Mesh(blinkGeo, red.clone());
  bowB.position.set(0, 0.052, -0.235);
  g.add(bowB);
  g.userData.blinkers.push(bowB);
  [-1, 1].forEach((s) => {
    const b = new THREE.Mesh(blinkGeo, amber.clone());
    b.position.set(s * 0.042, 0.032, 0.235);
    g.add(b);
    g.userData.blinkers.push(b);
  });

  return g;
}

export function buildWarship(THREE) {
  const g = new THREE.Group();
  g.userData.blinkers = [];
  const hull = new THREE.MeshStandardMaterial({ color: 0xccd3dd, metalness: 0.45, roughness: 0.4 });
  const dark = new THREE.MeshStandardMaterial({ color: 0x6b7480, metalness: 0.6, roughness: 0.5 });
  const deep = new THREE.MeshStandardMaterial({ color: 0x3a4149, metalness: 0.55, roughness: 0.6 });
  const windows = new THREE.MeshStandardMaterial({ color: 0x9fd8ff, emissive: 0x7fc4ff, emissiveIntensity: 0.7 });
  const amber = new THREE.MeshStandardMaterial({ color: 0xd89030, emissive: 0xff9920, emissiveIntensity: 1.2 });
  const red = new THREE.MeshStandardMaterial({ color: 0xff3018, emissive: 0xff2a10, emissiveIntensity: 2 });
  const cyan = new THREE.MeshStandardMaterial({ color: 0x3ec8ff, emissive: 0x2fb8ff, emissiveIntensity: 0.9 });

  // layered arrowhead primary hull (bow tip exactly at z = -0.175)
  const main = new THREE.Mesh(new THREE.BoxGeometry(0.15, 0.032, 0.2), hull);
  main.position.set(0, 0, -0.04);
  g.add(main);
  const nose = new THREE.Mesh(new THREE.BoxGeometry(0.06, 0.024, 0.08), hull);
  nose.position.set(0, 0, -0.135);
  g.add(nose);
  const topPlate = new THREE.Mesh(new THREE.BoxGeometry(0.11, 0.014, 0.15), deep);
  topPlate.position.set(0, 0.02, -0.03);
  g.add(topPlate);
  const belly = new THREE.Mesh(new THREE.BoxGeometry(0.1, 0.012, 0.13), dark);
  belly.position.set(0, -0.02, -0.03);
  g.add(belly);
  const chiselGeo = new THREE.BoxGeometry(0.05, 0.026, 0.13);
  [-1, 1].forEach((s) => {
    const ch = new THREE.Mesh(chiselGeo, dark);
    ch.position.set(s * 0.058, 0, -0.08);
    ch.rotation.y = s * 0.45;
    g.add(ch);
  });

  // bridge dome
  const bridgeBase = new THREE.Mesh(new THREE.CylinderGeometry(0.024, 0.03, 0.01, 24), dark);
  bridgeBase.position.set(0, 0.032, -0.05);
  g.add(bridgeBase);
  const dome = new THREE.Mesh(new THREE.SphereGeometry(0.018, 24, 16), hull);
  dome.scale.set(1, 0.55, 1);
  dome.position.set(0, 0.037, -0.05);
  g.add(dome);

  // engineering hull tucked under, amber deflector, impulse strip
  const engHull = new THREE.Mesh(new THREE.CylinderGeometry(0.02, 0.026, 0.13, 20), dark);
  engHull.rotation.x = Math.PI / 2;
  engHull.position.set(0, -0.032, 0.03);
  g.add(engHull);
  const deflector = new THREE.Mesh(new THREE.CylinderGeometry(0.013, 0.013, 0.008, 20), amber);
  deflector.rotation.x = Math.PI / 2;
  deflector.position.set(0, -0.032, -0.037);
  g.add(deflector);
  const impulse = new THREE.Mesh(new THREE.BoxGeometry(0.05, 0.012, 0.006), amber);
  impulse.position.set(0, 0.004, 0.062);
  g.add(impulse);

  // low-slung nacelles (aft caps end exactly at z = +0.175)
  const nacGeo = new THREE.CylinderGeometry(0.015, 0.015, 0.16, 20);
  const busGeo = new THREE.SphereGeometry(0.016, 16, 12);
  const grilleGeo = new THREE.BoxGeometry(0.003, 0.009, 0.115);
  const pylonGeo = new THREE.BoxGeometry(0.045, 0.009, 0.055);
  [-1, 1].forEach((s) => {
    const nac = new THREE.Mesh(nacGeo, hull);
    nac.rotation.x = Math.PI / 2;
    nac.position.set(s * 0.075, -0.012, 0.07);
    g.add(nac);
    const bus = new THREE.Mesh(busGeo, red);
    bus.position.set(s * 0.075, -0.012, -0.012);
    g.add(bus);
    const cap = new THREE.Mesh(busGeo, deep);
    cap.position.set(s * 0.075, -0.012, 0.159);
    g.add(cap);
    const pylon = new THREE.Mesh(pylonGeo, dark);
    pylon.position.set(s * 0.052, -0.01, 0.055);
    g.add(pylon);
    [-1, 1].forEach((t) => {
      const gr = new THREE.Mesh(grilleGeo, cyan);
      gr.position.set(s * 0.075 + t * 0.0155, -0.012, 0.075);
      g.add(gr);
    });
  });

  // lit window bands
  const wsGeo = new THREE.BoxGeometry(0.003, 0.007, 0.1);
  [-1, 1].forEach((s) => {
    const ws = new THREE.Mesh(wsGeo, windows);
    ws.position.set(s * 0.0755, 0, -0.05);
    g.add(ws);
  });
  const winGeo = new THREE.BoxGeometry(0.004, 0.003, 0.003);
  for (let i = 0; i < 6; i++) {
    const w = new THREE.Mesh(winGeo, windows);
    w.position.set((i - 2.5) * 0.011, 0.0285, -0.09);
    g.add(w);
  }

  // torpedo launcher greeble
  const torp = new THREE.Mesh(new THREE.BoxGeometry(0.024, 0.008, 0.016), deep);
  torp.position.set(0, -0.014, -0.15);
  g.add(torp);

  // 2 red blinkers at the wing tips
  const blinkGeo = new THREE.SphereGeometry(0.003, 10, 8);
  [-1, 1].forEach((s) => {
    const b = new THREE.Mesh(blinkGeo, red.clone());
    b.position.set(s * 0.105, 0.012, -0.03);
    g.add(b);
    g.userData.blinkers.push(b);
  });

  return g;
}

export function buildScout(THREE) {
  const g = new THREE.Group();
  g.userData.blinkers = [];
  const hull = new THREE.MeshStandardMaterial({ color: 0xccd3dd, metalness: 0.45, roughness: 0.4 });
  const dark = new THREE.MeshStandardMaterial({ color: 0x6b7480, metalness: 0.6, roughness: 0.5 });
  const deep = new THREE.MeshStandardMaterial({ color: 0x3a4149, metalness: 0.55, roughness: 0.6 });
  const windows = new THREE.MeshStandardMaterial({ color: 0x9fd8ff, emissive: 0x7fc4ff, emissiveIntensity: 0.7 });
  const amber = new THREE.MeshStandardMaterial({ color: 0xd89030, emissive: 0xff9920, emissiveIntensity: 1.2 });
  const red = new THREE.MeshStandardMaterial({ color: 0xff3018, emissive: 0xff2a10, emissiveIntensity: 2 });
  const cyan = new THREE.MeshStandardMaterial({ color: 0x3ec8ff, emissive: 0x2fb8ff, emissiveIntensity: 0.9 });

  // fuselage capsule + cone bow (tip exactly at z = -0.06)
  const fus = new THREE.Mesh(new THREE.CapsuleGeometry(0.008, 0.07, 6, 16), hull);
  fus.rotation.x = Math.PI / 2;
  fus.position.set(0, 0, 0.01);
  g.add(fus);
  const bow = new THREE.Mesh(new THREE.ConeGeometry(0.0078, 0.032, 16), hull);
  bow.rotation.x = -Math.PI / 2;
  bow.position.set(0, 0, -0.044);
  g.add(bow);

  // tail engine (nozzle exit exactly at z = +0.06)
  const nozzle = new THREE.Mesh(new THREE.CylinderGeometry(0.0065, 0.005, 0.012, 16), dark);
  nozzle.rotation.x = Math.PI / 2;
  nozzle.position.set(0, 0, 0.054);
  g.add(nozzle);
  const exhaust = new THREE.Mesh(new THREE.CylinderGeometry(0.0045, 0.0045, 0.0022, 16), amber);
  exhaust.rotation.x = Math.PI / 2;
  exhaust.position.set(0, 0, 0.0589);
  g.add(exhaust);

  // cockpit window band
  const band = new THREE.Mesh(new THREE.CylinderGeometry(0.0083, 0.0083, 0.005, 20), windows);
  band.rotation.x = Math.PI / 2;
  band.position.set(0, 0, -0.02);
  g.add(band);

  // dorsal nacelle on short pylon, cyan strip
  const pylon = new THREE.Mesh(new THREE.BoxGeometry(0.0035, 0.014, 0.018), dark);
  pylon.position.set(0, 0.013, 0.016);
  g.add(pylon);
  const nacelle = new THREE.Mesh(new THREE.CylinderGeometry(0.0052, 0.0052, 0.046, 14), hull);
  nacelle.rotation.x = Math.PI / 2;
  nacelle.position.set(0, 0.0235, 0.015);
  g.add(nacelle);
  const cyanStrip = new THREE.Mesh(new THREE.BoxGeometry(0.0014, 0.0035, 0.036), cyan);
  cyanStrip.position.set(0.0055, 0.0235, 0.015);
  g.add(cyanStrip);

  // tail fins
  const finGeo = new THREE.BoxGeometry(0.016, 0.0016, 0.009);
  [-1, 1].forEach((s) => {
    const fin = new THREE.Mesh(finGeo, deep);
    fin.position.set(s * 0.011, -0.001, 0.048);
    g.add(fin);
  });
  const vfin = new THREE.Mesh(new THREE.BoxGeometry(0.0016, 0.011, 0.013), deep);
  vfin.position.set(0, -0.01, 0.048);
  g.add(vfin);

  // single red blinker at the tail
  const blink = new THREE.Mesh(new THREE.SphereGeometry(0.0016, 8, 8), red.clone());
  blink.position.set(0, -0.0165, 0.052);
  g.add(blink);
  g.userData.blinkers.push(blink);

  return g;
}
